
http://127.0.0.1:3000/api/v1/products/

###
http://127.0.0.1:3000/api/v1/products/6

###
http://127.0.0.1:3000/api/v1/cart/mp@np

###
POST http://127.0.0.1:3000/api/v1/cart/mp@np/9/1

###
PATCH http://127.0.0.1:3000/api/v1/cart/mp@np.edu/6/5